### ISSUE TITLE
some comments from I-Hui 

### ISSUE THREAD

**Issue by rpedsel** [INF554Fall17/a7-sydtk#1]
Q1:
Should contain title for the presentation?
The arrows on the graph need to be altered a little bit...(aesthetic issue)
Q2:
There are watermark and URL on the image....
Q3:
The image chosen does not illustrate the idea we would like to present clearly? Also, the image is kind of blurred. Include some more detail about target audience may be better.
Q4:
Yeah, this one looks much better!
Q5:
Are there image for Q5?
Q6:
Should give out more detailed illustration rather than the simpler ones?

We can have further discussion below :)

**Comment by rpedsel** [comment]
As for Q10-15, there are a lot of really simple icons, kind of being too abstract? I am not sure if I also have the same problem... Maybe replace some image with more figurative ones would be better? On the other hand, I think maybe it is possible to keep the icons but with some more layout adjustments/alignments and squares or lines to guild audience (group up ideas of the same group, use lines/arrows to connect ideas)

**Comment by YiDomiChen** [comment]
I think the answers for Q2 and Q10 are similar. How could we differentiate them through slides? As for some questions such as technologies selection, I think there is no need to put figurative images. But for others, we need to revise so as to make the overall theme uniform.

**Comment by rpedsel** [comment]
I think it can be distinguished by of different level or different aspect, 
Like, in first one we can say, no one has done such comparison before and it is a information people would like to know. In the second one, we may describe what others have done in more detail and what we would like to build.

**Comment by cjshieh** [comment]
I fixed the question on Q1 to Q3 images.

**Comment by YiDomiChen** [comment]
Q10 - Q12, Q14 uploaded. I think contents of Q13 needs to be merged into Q15.
